### ISSUE TITLE
Update Main file for v.3176

### ISSUE THREAD

**Issue by fxbenard** [zam1024t/LocalizedMenu#16]
A few strings have been added to the latest version, it will be nice to be able to translate them

**Comment by zam1024t** [comment]
The ST menu v.3176 is as same as v.3170, [zh_CN/Zh_TW](https://github.com/zam1024t/LocalizedMenu/tree/master/menu/3170) has match the latest version.
Which version and language you are using, maybe you can submit a new pull request for your language?

**Comment by zam1024t** [comment]
https://github.com/zam1024t/LocalizedMenu/pull/17
Solved.
