### ISSUE TITLE
HOW TO REMOVE MENU LANGUAGE

### ISSUE THREAD

**Issue by hoangnamitc** [zam1024t/LocalizedMenu#2]
Hi adm, 

How to remove menu language in my ST3 !

Thanks !

![image](https://user-images.githubusercontent.com/7042462/29301194-a9c7343c-81a4-11e7-8d15-dabbe562d877.png)

**Comment by zam1024t** [comment]
Delete the menu file `Packages/LocalizedMenu/Main.sublime-menu` to solve.

**Comment by hoangnamitc** [comment]
Thanks for support. 
My problem resolved !
