### ISSUE TITLE
建议用户本地语言包以及设置信息放到User文件夹下

### ISSUE THREAD

**Issue by maboloshi** [zam1024t/LocalizedMenu#22]
建议用户本地语言包以及设置信息放到User文件夹下 `<Packages>\User\LocalizedMenu\`
实现包文件和用户文件分离 便于用户将`User`文件夹打包备份

**Comment by zam1024t** [comment]
1. 语言包实际保存在`Packages/LocalizedMenu/menu/<version>/<locale>/*.json`，`Packages/Default/*.sublime-menu`是动态生成的，且Sublime Text会自动加载并替换原生菜单。
2. 配置信息`Packages/User/LocalizedMenu.sublime-settings`已经是在`User`目录中了。
3. 语言包备份打包`Packages/LocalizedMenu/`整个目录就好了。

**Comment by maboloshi** [comment]
本来想把用户本地语言包以及设置信息放到User文件夹下，自己改造难度太大。
后来想想直接fork 把自己的翻译放进去就好了 ST直接添加fork的资源就OK了
