### ISSUE TITLE
How to translate dynamic menu entries?

### ISSUE THREAD

**Issue by Standarduser** [zam1024t/LocalizedMenu#24]
Hi,
I'm working on german translation and wondering how to translate dynamic texts.
E.g. View -> ... Minimap

If Minimap is shown the menu entry is "Hide Minimap". If Minimap is hidden the menu entry toggles to "Show Minimap". There are some more menu entries like this but none of them has a caption so I have no idea how to translate them:
```
			{ "command": "toggle_minimap" },
			{ "command": "toggle_tabs" },
			{ "command": "toggle_status_bar" },
			{ "command": "toggle_menu" },
```
Anyone have a hint for me?

**Comment by zam1024t** [comment]
Add "caption" after "command", like this:
https://github.com/zam1024t/LocalizedMenu/blob/master/menu/4126/zh_CN/Main.sublime-menu.json#L427

**Comment by Standarduser** [comment]
Just use "caption" like this makes the translation static, but the question was how to translate dynamic text that the translated text is also dynamic.

**Comment by OSPanel** [comment]
I think it's impossible, use a caption like here: `{ "command": "toggle_minimap", "caption": "Show/Hide Minimap" },`
