### ISSUE TITLE
Explanation of commands

### ISSUE THREAD

**Issue by Standarduser** [zam1024t/LocalizedMenu#25]
Hi,
I'm currently working on german translation and have problems with some strings, because I can't figure out what these functions do. Could someone help me to understand what following commands do so that I can find the correct german Translation?

Edit -> Text -> **Revert Hunk** (I don't understand what "Hunk" means)
Edit -> Text -> **Toggle Diff Hunk**

Edit -> Mark -> **Yank**

Thanks in advance.

**Comment by zam1024t** [comment]
My suggest is that you try to use this function, not care the name `hunk`, then give a name in german. 
As i understand "hunk" means text block.

About "Yank" the below links may help you:
https://forum.sublimetext.com/t/what-does-yank-mean-in-st3-v3114/21300
https://stackoverflow.com/questions/44467302/how-does-one-copy-an-arbitrary-block-of-text-in-sublime-text-3s-vintage-mode

**Comment by Standarduser** [comment]
Got it:
`toggle diff hunk` shows (or hides) the current line (or block) before it's modification underneath.
`revert hunk` reverts all modifications on the current line (or block)

`Yank` is something special coming from Linux editor `vi` and is like `cut & paste`
