### ISSUE TITLE
Huge menu

### ISSUE THREAD

**Issue by H2SO4JB** [zam1024t/LocalizedMenu#9]
Hi,
I don't know if this is a bug but after the evening's update of LocalizedMenu, the language
menu is huge, and contains duplicates of everything. See my screenshot. I've tested reinstalling
the LocalizedMenu package, but nothing helps. What's wrong?

![1](https://user-images.githubusercontent.com/13471707/33397197-3e9ebe0a-d54b-11e7-847a-0a5b318ce2d5.jpg)

**Comment by zam1024t** [comment]
Yeah, it is my mistake without full test before release.
`locale/sv_SE/LocalizedMenu.sublime-commands`
`locale/sv_SE/Main.sublime-menu`
Should not be upload.
ST will autoload them.

Now, I fix it, please use the new version v1.4.2.

**Comment by H2SO4JB** [comment]
Great, in V1.4.2 this menu looks good again.
But the 4 strings at the top of the menu are not translated. If I switch to Chinese for example, then
these 4 strings are also translated into Chinese. This is not important, but then you know.  :-)

![2](https://user-images.githubusercontent.com/13471707/33438237-821f7d8c-d5ea-11e7-936c-f6d3ac5180d6.jpg)

**Comment by zam1024t** [comment]
I has recovered the part of Swedish translation.

**Comment by H2SO4JB** [comment]
Okay, I understand.
As I said, it's not important.  :-)
Thanks for all you help.
